# Generated by Django 3.1.7 on 2021-05-02 14:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ToDoList',
            fields=[
                ('name', models.TextField(blank=True, default='Daily', help_text='Enter field documentation', primary_key=True, serialize=False, unique=True)),
                ('modified_timestamp', models.DateTimeField(auto_now=True)),
                ('created_timestamp', models.DateTimeField(auto_now_add=True)),
                ('priority', models.IntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'ToDoList',
                'verbose_name_plural': 'ToDoLists',
            },
        ),
        migrations.CreateModel(
            name='ListItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.TextField(blank=True, help_text='Enter field documentation', null=True)),
                ('modified_timestamp', models.DateTimeField(auto_now=True)),
                ('created_timestamp', models.DateTimeField(auto_now_add=True)),
                ('priority', models.CharField(choices=[('1', 'Low'), ('2', 'Medium'), ('3', 'Important'), ('4', 'Critical')], default='1', max_length=1)),
                ('to_do_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='taskapp.todolist')),
            ],
        ),
    ]
