# Generated by Django 3.1.7 on 2021-03-29 07:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('taskapp', '0004_auto_20210329_0713'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='todolist',
            options={'verbose_name': 'ToDoList', 'verbose_name_plural': 'ToDoLists'},
        ),
    ]
