# Generated by Django 3.1.7 on 2021-03-29 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskapp', '0007_auto_20210329_0734'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todolist',
            name='name',
            field=models.CharField(blank=True, help_text='Enter field documentation', max_length=20, null=True),
        ),
    ]
