# Generated by Django 3.1.7 on 2021-03-29 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskapp', '0008_auto_20210329_0808'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todolist',
            name='name',
            field=models.TextField(blank=True, help_text='Enter field documentation', null=True),
        ),
    ]
