# Generated by Django 3.1.7 on 2021-04-04 16:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('taskapp', '0022_items'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Items',
            new_name='Item',
        ),
    ]
