# Generated by Django 3.1.7 on 2021-04-05 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskapp', '0023_auto_20210404_1610'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='priority',
            field=models.CharField(choices=[('1', 'Low'), ('2', 'Medium'), ('3', 'Important'), ('4', 'Critical')], default='1', max_length=1),
        ),
    ]
