# Generated by Django 3.1.7 on 2021-04-05 09:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('taskapp', '0024_auto_20210405_0944'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Item',
            new_name='ListItem',
        ),
    ]
