# Generated by Django 3.1.7 on 2021-04-05 12:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('taskapp', '0025_auto_20210405_0956'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listitem',
            name='to_do_list',
            field=models.ForeignKey(db_column='name', on_delete=django.db.models.deletion.CASCADE, to='taskapp.todolist'),
        ),
    ]
