# Generated by Django 3.1.7 on 2021-05-06 05:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('taskapp', '0026_auto_20210405_1247'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listitem',
            name='to_do_list',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='taskapp.todolist'),
        ),
        migrations.AlterField(
            model_name='todolist',
            name='name',
            field=models.TextField(blank=True, default=1, help_text='Enter field documentation', unique=True),
            preserve_default=False,
        ),
    ]
